/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SecteursRouteImport } from './routes/secteurs'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CatalogueIndexRouteImport } from './routes/catalogue.index'
import { Route as CatalogueReferenceRouteImport } from './routes/catalogue.$reference'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'
import { Route as BlogCategorieCategoryRouteImport } from './routes/blog.categorie.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SecteursRoute = SecteursRouteImport.update({
  id: '/secteurs',
  path: '/secteurs',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueIndexRoute = CatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueReferenceRoute = CatalogueReferenceRouteImport.update({
  id: '/catalogue/$reference',
  path: '/catalogue/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorieCategoryRoute = BlogCategorieCategoryRouteImport.update({
  id: '/blog/categorie/$category',
  path: '/blog/categorie/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/secteurs': typeof SecteursRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalogue/$reference': typeof CatalogueReferenceRoute
  '/blog/': typeof BlogIndexRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/blog/categorie/$category': typeof BlogCategorieCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/secteurs': typeof SecteursRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalogue/$reference': typeof CatalogueReferenceRoute
  '/blog': typeof BlogIndexRoute
  '/catalogue': typeof CatalogueIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/blog/categorie/$category': typeof BlogCategorieCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/secteurs': typeof SecteursRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/catalogue/$reference': typeof CatalogueReferenceRoute
  '/blog/': typeof BlogIndexRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/blog/categorie/$category': typeof BlogCategorieCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/secteurs'
    | '/blog/$slug'
    | '/catalogue/$reference'
    | '/blog/'
    | '/catalogue/'
    | '/api/public/chat'
    | '/blog/categorie/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/secteurs'
    | '/blog/$slug'
    | '/catalogue/$reference'
    | '/blog'
    | '/catalogue'
    | '/api/public/chat'
    | '/blog/categorie/$category'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/secteurs'
    | '/blog/$slug'
    | '/catalogue/$reference'
    | '/blog/'
    | '/catalogue/'
    | '/api/public/chat'
    | '/blog/categorie/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  SecteursRoute: typeof SecteursRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CatalogueReferenceRoute: typeof CatalogueReferenceRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CatalogueIndexRoute: typeof CatalogueIndexRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  BlogCategorieCategoryRoute: typeof BlogCategorieCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secteurs': {
      id: '/secteurs'
      path: '/secteurs'
      fullPath: '/secteurs'
      preLoaderRoute: typeof SecteursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/': {
      id: '/catalogue/'
      path: '/catalogue'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof CatalogueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/$reference': {
      id: '/catalogue/$reference'
      path: '/catalogue/$reference'
      fullPath: '/catalogue/$reference'
      preLoaderRoute: typeof CatalogueReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/categorie/$category': {
      id: '/blog/categorie/$category'
      path: '/blog/categorie/$category'
      fullPath: '/blog/categorie/$category'
      preLoaderRoute: typeof BlogCategorieCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  SecteursRoute: SecteursRoute,
  BlogSlugRoute: BlogSlugRoute,
  CatalogueReferenceRoute: CatalogueReferenceRoute,
  BlogIndexRoute: BlogIndexRoute,
  CatalogueIndexRoute: CatalogueIndexRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  BlogCategorieCategoryRoute: BlogCategorieCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
